import React from 'react'
import {
  BookMarked,
  BookOpen,
  Calculator,
  Code2,
  Cpu,
  GraduationCap,
  Database,
  BarChart2,
  PenTool,
  Terminal,
  Folder,
  Lightbulb,
  ShieldCheck,
  Globe,
  Palette,
  TrendingUp,
  Network,
  Settings,
  Braces,
  Bug,
  Rocket,
  Zap,
  Clock,
  CloudCheck,
  Atom,
  Dna,
  Binary,
  Microscope,
  FlaskConical,
  Sigma,
  LucideIcon,
} from 'lucide-react'

interface IconRendererProps {
  icon: string
  className?: string
  size?: number
}

const ICON_MAP: Record<string, LucideIcon> = {
  'journal-bookmark': BookMarked,
  'book-open': BookOpen,
  'calculator': Calculator,
  'code': Code2,
  'cpu': Cpu,
  'mortarboard': GraduationCap,
  'database': Database,
  'chart-bar': BarChart2,
  'pen-tool': PenTool,
  'terminal': Terminal,
  'folder': Folder,
  'lightbulb': Lightbulb,
  'shield': ShieldCheck,
  'globe': Globe,
  'palette': Palette,
  'graph-up': TrendingUp,
  'diagram': Network,
  'gear': Settings,
  'braces': Braces,
  'bug': Bug,
  'rocket': Rocket,
  'lightning': Zap,
  'clock': Clock,
  'cloud': CloudCheck,
  'atom': Atom,
  'dna': Dna,
  'math': Sigma,
  'microchip': Binary,
  'flask-conical': FlaskConical,
  'microscope': Microscope,
}

export const IconRenderer: React.FC<IconRendererProps> = ({ icon, className = '', size = 20 }) => {
  const IconComponent = ICON_MAP[icon] || BookMarked
  return <IconComponent className={className} size={size} />
}

export const ALL_UNIVERSITY_ICONS: Array<{ id: string; label: string; group: string }> = [
  { id: 'journal-bookmark', label: 'Libreta Universitaria', group: 'General' },
  { id: 'book-open', label: 'Libro de Texto', group: 'General' },
  { id: 'mortarboard', label: 'Graduación / Carrera', group: 'General' },
  { id: 'calculator', label: 'Cálculo y Matemáticas', group: 'Ciencias' },
  { id: 'math', label: 'Fórmulas y Álgebra', group: 'Ciencias' },
  { id: 'atom', label: 'Física y Química', group: 'Ciencias' },
  { id: 'dna', label: 'Biología y Medicina', group: 'Ciencias' },
  { id: 'flask-conical', label: 'Laboratorio y Prácticas', group: 'Ciencias' },
  { id: 'microscope', label: 'Investigación y Salud', group: 'Ciencias' },
  { id: 'code', label: 'Programación', group: 'Ingeniería' },
  { id: 'braces', label: 'Algoritmos y Código', group: 'Ingeniería' },
  { id: 'terminal', label: 'Terminal / Consola', group: 'Ingeniería' },
  { id: 'database', label: 'Bases de Datos', group: 'Ingeniería' },
  { id: 'cpu', label: 'Arquitectura de Computadoras', group: 'Ingeniería' },
  { id: 'microchip', label: 'Sistemas Embebidos y Binario', group: 'Ingeniería' },
  { id: 'diagram', label: 'Estructuras y Redes', group: 'Ingeniería' },
  { id: 'shield', label: 'Ciberseguridad', group: 'Ingeniería' },
  { id: 'lightning', label: 'Circuitos Eléctricos', group: 'Ingeniería' },
  { id: 'gear', label: 'Ingeniería Industrial', group: 'Ingeniería' },
  { id: 'chart-bar', label: 'Estadística y Finanzas', group: 'Negocios' },
  { id: 'graph-up', label: 'Economía y Proyectos', group: 'Negocios' },
  { id: 'palette', label: 'Diseño y Arte', group: 'Creatividad' },
  { id: 'pen-tool', label: 'Redacción y Ensayos', group: 'Creatividad' },
  { id: 'globe', label: 'Idiomas y Geografía', group: 'Humanidades' },
  { id: 'lightbulb', label: 'Innovación / Tesis', group: 'General' },
  { id: 'rocket', label: 'Proyecto Final', group: 'General' },
]
